### ISSUE TITLE
Add option for mapping Amplitude time field

### ISSUE THREAD

**Issue by laziob** [snowplow/snowplow-gtm-server-side-amplitude-tag#13]
Amplitude's way of ordering events by default is using the `client_event_time` which happens at the time Amplitude processes the event.

But if you want to override that behaviour for some reason, they let you do it by overriding the _time field of the event payload.

Right now we have a case that some of our events ingested through the tag are being processed in the incorrect order by Amplitude.
For example:
For quiz_finished event:
This event on the stream looks like it was fired before quiz_question_answered. That is because the `client_event_time` of this event is lower than the `client_event_time` of the quiz_question_answered event (second screenshot)
<img width="689" alt="image" src="https://user-images.githubusercontent.com/22123425/178586212-f1355500-821a-4ab7-996c-21adc15e5c9c.png">

quiz_question_answered:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/22123425/178586533-3c9686c0-a17f-4507-8d10-b20cde4b0b4a.png">

Instead if you look at the green timestamp, the event_timestamp we are sending as an event_prop, those work as intended, where the quiz_question_answered timestamp is lower than the quiz_finished (that is the right behaviour on the web).

So if we can be able to map the green event_timestamp to the _time field we would be able to solve this issue, since Amplitude doesnt  have a way to override it or use a separate timestamp field for their order calculations.

Thanks!

**Comment by laziob** [comment]
@adatzer @paulboocock Hi! 

I created this fork: https://github.com/laziob/snowplow-gtm-server-side-amplitude-tag/blob/adding_timestamp_setting_option/template.tpl in order to address this.

So far, I manage to get it working when running the test on GTM SS template editor, but it still didnt override the `_time` field on Amplitude side. And then for some reason the GTM Template Editor tests stopped working, it just throws me "Internal Error - No tests were run".

If by any chance you can try this out and let me know what your result is that would be great!

Thanks a lot!

**Comment by adatzer** [comment]
Hi @laziob ! 
We are currently working towards the next release of the Tag, so we'll definitely try this out and let you know as soon as possible.

**Comment by laziob** [comment]
> Hi @laziob ! We are currently working towards the next release of the Tag, so we'll definitely try this out and let you know as soon as possible.

Awesome Thanks!!!
Sorry for the push here but I'll be leaving my current employer by end of month so Im trying my best to give them some tools and alternatives at least to address some of the current pipeline issues however they see fit, this being the most pressing one.

Thanks for the fast response :D
