### ISSUE TITLE
Set the Amplitude Session ID from client session context

### ISSUE THREAD

**Issue by adatzer** [snowplow/snowplow-gtm-server-side-amplitude-tag#5]
Currently, the top level `session_id` of an Amplitude event (which corresponds to the default Amplitude SessionID) is not mapped by default (e.g. to Snowplow `domain_sessionid`).

So, at the moment in order to map Snowplow session information to Amplitude session information, someone would need for example to:

1. Map the `x-sp-domain_sessionid` to `session_id` using the Additional Event Property Mapping Rules section in tag configuration (which can only populate an `event_properties` field).
2. Change the session definition for the Amplitude project to use this `session_id` from the Amplitude Event Properties, as described [here](https://help.amplitude.com/hc/en-us/articles/115002323627-Track-sessions-in-Amplitude#h_d6df9d70-48fa-44cb-8907-7c3c652b007f).

Would it make sense to consider adding a configuration option in the tag that directly populates the default Session ID (top-level `session_id` field in Amplitude event)?

**Comment by paulboocock** [comment]
The HTTP API V2 docs for Amplitude state that `session_id` should be a `long`. 

https://developers.amplitude.com/docs/http-api-v2

This is why I didn't map the `domain_sessionid` to this value as it isn't compatible. Unless it actually is and the docs aren't correct. 

I wasn't sure what to use instead, as we don't have a `long` session identifier. Thoughts?

**Comment by adatzer** [comment]
I completely missed this! 
Indeed, the Amplitude docs are correct, just tried with a uuid and fails:

```
{"code":400,"events_with_invalid_fields":{"session_id":[0]},"error":"Invalid field values on some events"}
```

**Comment by laziob** [comment]
I ended up mapping the `domain_sessionid` to a `snowplow_sessionid` event property within Amplitude, and config Amplitude to use that as the Session ID and it works. So it wouldn't seem that the format is an issue, unless Amplitude does some kind of format change or parsing after the JSON is ingested.

**Comment by adatzer** [comment]
Hey @laziob !
Thanks for confirming that it works!
Just a question: Do you now actually see the `Session ID` populated by the new value? 
In my tries so far, when changing the session definition, i was still seeing the `Session ID` as `-1`, but the events are correctly attributed on same session. In other words, the session definition was switched from `Session ID` to, say, `snowplow_sessionid`, but the `Session ID` itself was not altered.

**Comment by laziob** [comment]
@adatzer Oh its the same as what you describe on my case. See pic attached. 
<img width="705" alt="image" src="https://user-images.githubusercontent.com/22123425/168305910-8f86f229-6733-421c-b4c4-a91257c4686f.png">

So yes, the default session_id from Amplitude does not change. Which seem to incur some product issues like not being able to do Session Counts by device / user like shown below:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/22123425/168306154-c334369d-1d88-454c-b1b9-f1c7788c7962.png">

So being able to map the domain_sessionid (or any other) to the real session_id property should fix this I believe.

**Comment by laziob** [comment]
Broadly speaking, It might be good for the template to have an optional way to set or map all or some of the default User Properties listed here:
https://help.amplitude.com/hc/en-us/articles/215562387-Appendix-Amplitude-User-Property-Definitions
with properties from the Snowplow JSON (either common event data or custom)

**Comment by paulboocock** [comment]
We've got a few ideas we're hoping to run with in the next month or two across our trackers. 
- We want to introduce the session start time to the `client_session` schema, this will allow us to create a suitable `long` session_id for downstream tools like Amplitude. 
- We'll also introduce `client_session` to the JS Tracker.
