### ISSUE TITLE
Add option to include or exclude an entity

### ISSUE THREAD

**Issue by laziob** [snowplow/snowplow-gtm-server-side-amplitude-tag#6]
Right now the user can either include all entities in the `event_properties` object, or can map if specific entities are to be sent to the `event_properties` or `user_properties` object instead, while having the rest of the unmapped entities either sent or not. Like in the pic below
<img width="735" alt="image" src="https://user-images.githubusercontent.com/22123425/168324667-3ce818a4-4edc-4959-b52a-ce7d07992451.png">

The issue with this approach is that, if I wanted to exclude just one entity, I would have to uncheck the "Include unmapped entities" option, and map every remaining entity that I would like to include. If instead we could "exclude" entities, that would be much easier and less maintenance in the future.

**Comment by paulboocock** [comment]
Great suggestion! This would be one for all our templates with this functionality.
