### ISSUE TITLE
Add version control naming as an option

### ISSUE THREAD

**Issue by laziob** [snowplow/snowplow-gtm-server-side-amplitude-tag#7]
Right now, if one maps an entity or key name to some other value, one has to detail the key name entirely, up to the version digit, like:
`x-sp-contexts_com_penrosehill_user_1`

It would be great to have some kind of "version control" flag that would let you just state the name of the entity up to just before the version control. That way if there is an entity or key that you will want to map to an Amplitude property no matter what, it would be required to maintain the mapping version in the GTM tag each time the major version changes.

I know that major versions changes shouldn't be that frequent, but I'm trying to place myself in the shoes of an end user which is asked to maintain all this without being too tech savvy, where flexibility provides more value than straight strictness (while strictness should still be kept as the default IMO)

**Comment by paulboocock** [comment]
I assume this is pretty safe in Amplitude @laziob because it doesn't really care about the schema of the event, it'll take any unstructured JSON, right?

**Comment by laziob** [comment]
@paulboocock exactly. Even more, if I leave the contexts (entities) included in the event properties object, once a major version changes for a context, if I pick an event that includes that, it will suddenly stop having the event property xxxx_1 and start having xxxxx_2. So working with current and past data from Amplitude becomes more difficult for the end user.
